name: 'Build Images'
description: 'Docker Build Images'
inputs:
    arch:
        description: 'OS architecture'
        required: true
    dotnet_version:
        description: '.net version'
        required: true
    dotnet_variant:
        description: '.net variant'
        required: true
    docker_distro:
        description: 'Linux Distro'
        required: true
    docker_registry:
        description: 'Docker Registry'
        required: true
    docker_registry_name:
        description: 'Docker Registry Name'
        required: true
    docker_registry_username:
        description: 'Docker Registry Username'
        required: true
    docker_registry_password:
        description: 'Docker Registry Password'
        required: true

runs:
    using: 'composite'
    steps:
        -   name: Login to ${{ inputs.docker_registry }}
            if: ${{ env.PUSH_IMAGES == 'true' }}
            uses: docker/login-action@v3
            with:
                registry: ${{ inputs.docker_registry }}
                username: ${{ inputs.docker_registry_username }}
                password: ${{ inputs.docker_registry_password }}
        -   name: '[Build Docker images] ${{ inputs.docker_registry }}'
            shell: pwsh
            run: |
                dotnet run/build.dll `
                    --target=DockerBuildImages --arch=${{ inputs.arch }} `
                    --dotnet_version=${{ inputs.dotnet_version }} --dotnet_variant=${{ inputs.dotnet_variant }} `
                    --docker_distro=${{ inputs.docker_distro }} --docker_registry=${{ inputs.docker_registry_name }} `
                    --push_images=${{ env.PUSH_IMAGES }} --verbosity=diagnostic
