ARG DISTRO='debian-9'
ARG DOTNET_VERSION='2.1'
ARG VERSION='5.3.7'

FROM gittools/build-images:$DISTRO-sdk-$DOTNET_VERSION as installer
ARG contentFolder
ARG VERSION

WORKDIR /app
COPY $contentFolder/ ./
RUN dotnet tool install GitVersion.Tool --version $VERSION --tool-path /tools

FROM gittools/build-images:$DISTRO-runtime-$DOTNET_VERSION

WORKDIR /tools
COPY --from=installer /tools .

ENTRYPOINT ["/tools/dotnet-gitversion"]
