trigger:
- none

stages:

- template: recovery.tmpl.yml
  parameters:
    vmImage: 'ubuntu-latest'
    os: 'linux'
    distros: [ alpine.3.10-x64, centos.7-x64, debian.9-x64, fedora.30-x64, ubuntu.16.04-x64, ubuntu.18.04-x64 ]
    versions: [ '2.1', '3.1' ]
    tags: [ '5.1.3', '5.2.0', '5.2.1', '5.2.2', '5.2.3', '5.2.4', '5.3.0', '5.3.1', '5.3.2', '5.3.3', '5.3.4', '5.3.5', '5.3.6', '5.3.7', '5.5.0', '5.5.1' ]

- template: recovery.tmpl.yml
  parameters:
    vmImage: 'windows-latest'
    os: 'windows'
    distros: [ nanoserver ]
    versions: [ '2.1', '3.1' ]
    tags: [ '5.1.3', '5.2.0', '5.2.1', '5.2.2', '5.2.3', '5.2.4', '5.3.0', '5.3.1', '5.3.2', '5.3.3', '5.3.4', '5.3.5', '5.3.6', '5.3.7', '5.5.0', '5.5.1' ]
