version: 2
updates:
  - package-ecosystem: dotnet-sdk
    labels:
      - "dependencies"
    commit-message:
      prefix: "(sdk)"
    directory: "/build"
    schedule:
      interval: cron
      cronjob: "0 12 * * *"
  - package-ecosystem: nuget
    labels:
      - "dependencies"
    commit-message:
      prefix: "(deps)"
    directory: "/build"
    schedule:
      interval: cron
      cronjob: "0 12 * * *"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    labels:
      - "dependencies"
    commit-message:
      prefix: "(build deps)"
    directory: "/"
    schedule:
      interval: cron
      cronjob: "0 12 * * *"

  - package-ecosystem: nuget
    directory: /build/build
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/linux
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/linux/alpine.3.23
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/linux/centos.stream.9
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/linux/debian.12
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/linux/fedora.43
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/linux/ubuntu.22.04
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/linux/ubuntu.24.04
    schedule:
      interval: daily
