schedules:
- cron: "0 12 * * *"
  displayName: Daily build
  always: true
  branches:
    include:
    - master

jobs:

- template: jobs.yml
  parameters:
    name: Linux
    vmImage: 'Ubuntu 16.04'

- template: jobs.yml
  parameters:
    name: Windows
    vmImage: 'windows-2019'
