schedules:
- cron: "0 12 * * *"
  displayName: Daily build
  always: true
  branches:
    include:
    - main

stages:

- template: jobs.yml
  parameters:
    vmImage: 'ubuntu-latest'
    distros: [ alpine.3.12-x64, centos.7-x64, centos.8-x64, debian.9-x64, debian.10-x64, fedora.33-x64, ubuntu.16.04-x64, ubuntu.18.04-x64, ubuntu.20.04-x64 ]
    versions: [ 3.1, 5.0 ]
    variants: [ sdk, runtime ]
