stages:
- ${{ each variant in parameters.variants }}:
    - ${{ each version in parameters.versions }}:
        - stage:
          dependsOn: []
          displayName: '${{ variant }}:${{ version }}'
          jobs:
          - ${{ each distro in parameters.distros }}:
            - job:
              displayName: '${{ distro }}'
              pool:
                vmImage: ${{ parameters.vmImage }}
              steps:
                - pwsh: ./build.ps1 -script build.cake -target Default -version ${{ version }} -variant ${{ variant }} -distro ${{ distro }}
                  displayName: 'Cake build'
                  env:
                    DOCKER_USERNAME: $(DOCKER_USERNAME)
                    DOCKER_PASSWORD: $(DOCKER_PASSWORD)
