name: 'Docker Setup'
description: 'Setups the docker engine'

runs:
    using: 'composite'
    steps:
        -   name: Set up Docker
            uses: docker/setup-docker-action@v4
            with:
                daemon-config: '{ "features": { "containerd-snapshotter": true } }'
        -   name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v3
            with:
                version: 'latest'
                driver-opts: 'image=moby/buildkit:buildx-stable-1'
                install: true
