FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
# Pre-requisits
RUN apk update && apk --no-cache add bash ca-certificates-bundle git icu-libs libgcc libssl3 libstdc++ wget zlib
