FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40
# Pre-requisits
RUN apk update && apk --no-cache add bash ca-certificates-bundle git icu-libs libgcc libssl3 libstdc++ wget zlib
